name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_multi_formatter: ^2.13.0
  sqflite: 2.4.0
  path: 1.9.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.5.0

flutter:
  uses-material-design: true